Hw1 cleancode
GenesisEducationKyiv/main-project-stupidcucumber pull request #2
Opened 2023-06-19 06:58 UTC by stupidcucumber

1) Added linter to the GitHub actions
2) Refactored major part of the code accordingly to the clean code rules
3) Implemented chain responsibility through Interfaces

2023-06-20 22:20 UTC, andrii-kosinskyi requested changes
Very well structured code base, I think this code will be easy cover test and maintain!
I added some minor changes what you can change or we can discuss about my advices.

2023-06-20 22:20 UTC, andrii-kosinskyi commented on models/coingecko_price.go
> +	value := p.Rates["uah"].Value
Can we move `"uah"` up to const initialization as `main Currency` for example? it can add for as more flexible code and we removing `magic words` from our code.

2023-06-20 22:20 UTC, andrii-kosinskyi commented on templates/template.html
> +            h1
Can we use some formatter for this html file? 
Strange formatted in `<style> ` also we have inline styles, i think we can aggregate all css in `<style> ` tag.

2023-06-20 22:20 UTC, andrii-kosinskyi commented on models/binance_price.go
> +	finalURL := fmt.Sprintf("%v", u)
Why you prefer use `%v` there but not `%s`?

2023-06-20 22:20 UTC, andrii-kosinskyi commented on models/binance_price.go
> +		return invalidPrice, fmt.Errorf("unmarshalling exchange rate object: %v", err)
In case above you add `\n` at the end of line. Why don't you prefer to add it in this case?

2023-06-20 22:20 UTC, andrii-kosinskyi commented on handler/subscribe.go
> +func PostSubscribe(c *gin.Context) {
It is best practice add prefix `Post`, `Get`, `Patch` for gin?

2023-06-20 22:20 UTC, andrii-kosinskyi commented on controller/file_manager.go
> +func init() {
I see what you use very often `init()` almost in all `.go` file as I know it is not good idea, do you know something about it?

2023-06-21 10:15 UTC, stupidcucumber commented on controller/mail_manager.go
> +			fmt.Fprintf(os.Stderr, "Error while sending to %s occured: %v", emails[i], err)
That's my bad, actually, following the documentation of Go `%v` is used, when we have to print out a struct. In this case, where I am just only printing out the error `%s` format specifier will work well. However, Documentation still suggests to use `%v` for printing out errors, 

However, while I was reading through my code I noticed that maybe it's better for a functions to return errors, rather than just printing out them. In this way we can trace our error from the root to the first function we've called.

So my code now looks like this in places where it is crucial to return error back (for example if we couldn't extract emails at all): 
```suggestion
			return fmt.Errorf("Error while sending to %s occured: %w", emails[i], err)
```

In places, where I have no need to return error I would rather stick to the `%v` specifier. `%s` in most cases is OK, but `%v` is more preferable if err is `nil`. Also if you check the [documentation](https://go.dev/blog/error-handling-and-go), go team also prefer to use `%v` over `%s`.

2023-06-21 10:20 UTC, stupidcucumber commented on models/coingecko_price.go
> +	value := p.Rates["uah"].Value
I see, you're right! I also checked other parts of my code for magic numbers and changed it. Now I have constant "currency" at the top of the file. And now it looks like:
```suggestion
	value := p.Rates[currency].Value
```

2023-06-21 10:27 UTC, stupidcucumber commented on models/binance_price.go
> +		return invalidPrice, fmt.Errorf("unmarshalling exchange rate object: %v", err)
Yep, I don't know why :D . I removed all the '\n' from all places, where an error is being print to os.Stdout, so that my code will be more consistent.

2023-06-21 10:42 UTC, stupidcucumber commented on controller/file_manager.go
> +func init() {
Actually, it is! I needed those `init()` to load all .env variables that I will need, but I came up with better solution: add a new function to the helpers:
```go
package helpers


import (
	"fmt"
	"log"
	"os"

	"github.com/joho/godotenv"
)

func GetEnvVariable(key string) (string, error) {
	if err := godotenv.Load(); err != nil {
		log.Print("No .env file found")
		return "", err
	}

	result, present := os.LookupEnv(key)
	if !present {
		return "", fmt.Errorf(".env variable with key %s doesn't exist", key)
	}

	return result, nil
}
```

In this way I can just call the function when I need an .env variable, instead of blindly load all variables upon initialization. Thank you!

2023-06-21 12:22 UTC, stupidcucumber commented on handler/subscribe.go
> +func PostSubscribe(c *gin.Context) {
If you follow [this](https://go.dev/doc/tutorial/web-service-gin) official documentation on Gin Framework, you will notice that they use prefixes `Post`, `Get`, `Update` and other to indicate which method handler will catch. Therefore I consider such convention as canonical!

2023-06-21 12:24 UTC, stupidcucumber commented on controller/file_manager.go
> +func getEmails() []string {
Hmmm.. Your guess is that `extractEmails` would be better? :)

2023-06-21 16:02 UTC, stupidcucumber commented on models/coingecko_price.go
> +	u, err := url.ParseRequestURI(httpsGeeko)
I removed it completely and now URL generate another special function.

2023-06-21 16:03 UTC, stupidcucumber commented on models/binance_price.go
> +	finalURL := fmt.Sprintf("%v", u)
Instead of `fmt.Sprintf(...)` I now use method `u.String()` so struct url decides how to convert to the string itself.

2023-06-22 15:03 UTC, andrey-filenko-quarks-tech commented on Dockerfile
> +COPY . ./
nice optimization for builds would be 
```
COPY ./go.mod ./go.mod
COPY ./go.mod ./go.mod

RUN go mod download

COPY . .
```

that all your dependencies would be cached in a docker layer

2023-06-22 15:04 UTC, andrey-filenko-quarks-tech commented on README.md
> +# bitcoin-api
nice readme

2023-06-22 15:08 UTC, andrey-filenko-quarks-tech commented on controller/file_manager.go
> +	"api/bitcoin-api/helpers"
please, do not use "helpers" naming for packages, for people who are unfamiliar with project there is a big possibility to put everything there

2023-06-22 15:12 UTC, andrey-filenko-quarks-tech commented on controller/file_manager.go
> +	if helpers.ValidateEmail(email.Email) && !isPresent {
please, use "fail fast" approach, you can refactor this code like
```
if !helpers.ValidateEmail(email.Email) || isPresent {
    return fmt.Errorf("provided email is invalid")
} 

if _, err := f.WriteString(email.Email + "\n"); err != nil {
    return fmt.Errorf("the writing to the file went wrong: %w", err)
}

return nil
```

2023-06-22 15:12 UTC, andrey-filenko-quarks-tech commented on controller/mail_manager.go
> +	t, _ := template.ParseFiles("templates/template.html")
unchecked error

2023-06-22 20:35 UTC, stupidcucumber commented on controller/file_manager.go
> +	"api/bitcoin-api/helpers"
I don't know how to name it, 'cause pure purpose of this package is to contain self-contained functions (as I understand, they are barely depend on third-party tools and do not depend on my project modules/packages). Whole day I thought about how to name it, but only came up with name "tools". May be you can suggest something better, please? :)

2023-06-22 20:58 UTC, stupidcucumber commented on controller/mail_manager.go
> +	t, _ := template.ParseFiles("templates/template.html")
Changed

2023-06-22 20:58 UTC, stupidcucumber commented on controller/file_manager.go
> +	if helpers.ValidateEmail(email.Email) && !isPresent {
Thanks, refactored this piece of code

2023-06-22 20:58 UTC, stupidcucumber commented on controller/mail_manager.go
> +	port, _ := strconv.ParseInt(emailCredentials.PortSMTP, 10, 64)
Changed

2023-06-22 20:59 UTC, stupidcucumber commented on Dockerfile
> +COPY . ./
Thanks! For some time I was really bored waiting while docker is downloading dependencies :D

2023-06-23 08:15 UTC, andrey-filenko-quarks-tech commented on controller/file_manager.go
> +	"api/bitcoin-api/helpers"
I guess all this helpers methods have some bounding context, for example validator can be in validate package

2023-06-23 20:31 UTC, stupidcucumber commented on controller/file_manager.go
> +	"api/bitcoin-api/helpers"
I splited tools into validators package and loaders package

2023-06-30 08:44 UTC, merged